### ISSUE TITLE
Backender is not working

### ISSUE THREAD

**Issue by bhytam** [MahdiHoseinpoor/Backender#2]
I want to test, but is not working. 
I have the error bellow:

Enter your Configuration File Location: D://Backender/configs/GoBlog.yaml
 --- D://Backender/configs/GoBlog.yaml -> The Config File Processing has been start
    ErrorCode | Description 
        BA901 | The SavePath is null, your Solution will Create in 'Documents/Backender 2023/Sources'
 
        Backender Engine Start to Generate!
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Backender.CodeGenerator.Patterns.Repo.DtoHandler.ImplementFactory(Class entityFactory, String entityCategory) in E:\Creations of my Mind\Palokino\Programmings\Backender\src\Backender.CodeGenerator\Patterns\Repo\DtoHandler.cs:line 207
   at Backender.CodeGenerator.Patterns.Repo.DtoHandler.AddPrepareMethod(Class entityFactory, Entity entity, Project coreProj, List`1 entities) in E:\Creations of my Mind\Palokino\Programmings\Backender\src\Backender.CodeGenerator\Patterns\Repo\DtoHandler.cs:line 141
   at Backender.CodeGenerator.Patterns.Repo.DtoHandler.FactoriesGenerate(List`1 entities, Project& proj, Project coreProj) in E:\Creations of my Mind\Palokino\Programmings\Backender\src\Backender.CodeGenerator\Patterns\Repo\DtoHandler.cs:line 89
   at Backender.CodeGenerator.Patterns.Repo.RepoPatternGenerator.Run() in E:\Creations of my Mind\Palokino\Programmings\Backender\src\Backender.CodeGenerator\Patterns\Repo\RepoPatternGenerator.cs:line 77
   at Backender.CodeGenerator.Engine.Run(Config config) in E:\Creations of my Mind\Palokino\Programmings\Backender\src\Backender.CodeGenerator\Engine.cs:line 33
   at Backender.ConsoleApp.Program.Main(String[] args) in E:\Creations of my Mind\Palokino\Programmings\Backender\src\Backender.CLI\Program.cs:line 70
   at Backender.ConsoleApp.Program.<Main>(String[] args)

**Comment by MahdiHoseinpoor** [comment]
fixed in v1.2.2
